DEBUG 2020-12-28 13:38:35.126 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-12-28 13:38:35.126 UTC: 	 Running on: Linux ui03.recas.ba.infn.it 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-12-28 13:38:35.126 UTC: 	 Executing command: 'status'
DEBUG 2020-12-28 13:38:35.128 UTC: 	 Found CRAB cache file /lustre/home/welmetenawee/.crab3
ERROR 2020-12-28 13:38:35.129 UTC: 	 Error: 'crab status' command accepts at most 1 argument (a path to a CRAB project directory), 3 given.
ERROR 2020-12-28 13:38:35.129 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 614, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: 'crab status' command accepts at most 1 argument (a path to a CRAB project directory), 3 given.
INFO 2020-12-28 13:38:35.135 UTC: 	 Log file is /lustre/home/welmetenawee/NEW_Framework/Legacy_2018/CMSSW_10_2_22/src/crab.log
